export const colors = [
  'red',
  'blue',
  'yellow',
  'green',
  'purple',
  'pink',
  'orange',
  'aqua'
];

export const duration = {
  "Short": 20,
  "Medium": 30,
  "Long": 40,
  "Infinite": 1000
}

export const minigames = [
  {
    title: 'Categories',
    completed: 'Losing',
    directions: 'Go around the circle in turn.\nEach player or team has 3 seconds to name\nan item from the category',
    style: {},
    multipleChoice: true,
    modes: ['FFA', 'team', 'duel'],
    topics: [
      'Beer Brands',
      'Dog Breeds',
      'Country Capitals',
      'Animals',
      'Fruits',
      'Vegetables',
      'Languages',
      'Plants',
      'Sports',
      'Game Consoles',
      'Board Games',
      '90s TV Shows',
      'Types of Fish',
      'Cereal Brands',
      'Fast Food Chains',
      'Famous Dead Musicians',
      'NBA Teams',
      'NFL Teams',
      'Baseball Teams',
      'Movie Directors',
      'African Countries',
      'Superheroes',
      'European Capitals',
      'Disney Princesses',
      'Flowers',
      'Types of Candy',
      'Asian Countries',
      'South American Countries',
      'Private Colleges',
      'Celebrity Couples'
    ]
  },
  {
    title: 'Taboo',
    completed: 'Winning',
    directions: 'You will give hints to everyone for the secret word.\nYou cannot say rhyming words or words that are in the "excluded" list.\nThe first person to shout out the correct answer wins',
    modes: ['FFA'],
    style: {fontSize: 20},
    topics: [
      'Baseball',
      'Sunset',
      'Chair',
      'Firework',
      'Kiss',
      'Television'
    ],
    subtopics: [
      'Excluded: Homerun, Strike, Pitch, Bat, Glove',
      'Excluded: Sun, Evening, Sky',
      'Excluded: Seat, Sit, Recliner',
      'Excluded: July, Celebrate, Explosion, Colorful',
      'Excluded: Make-Out, Lips, Tongue, French, Hug',
      'Excluded: TV, Watch, Movie, Netflix',
    ]
  },
  {
    title: 'Trivia',
    completed: 'Winning',
    directions: 'Pick up the phone to hide the answer.\nRead the trivia question aloud.\nThe first person to shout out the correct answer wins',
    style: {},
    modes: ['FFA'],
    topics: [
      'What is the capital of New York?',
      'Who is the Prime Minister of Canada?',
      'What famous figure was killed on November 22, 1963?',
      'What is the deadliest mammal in Africa?',
      'What is Harry Potter\'s aunt\'s name?',
      'What is the richest country in Africa?',
      'Who did Chandler marry in Friends?',
      'What is the scientific term for -273 degrees Celsius?',
      'Who is the American Secretary of State?',
      'How many squares are there on a chess board?',
      'Which historical prince was used in Bram Stoker\'s famous novel?',
      'Which actor was also known as "The Tramp"?',
      'Which soccer player made the most money in 2017?',
      'Which team won the NBA championships in 2017?',
      'Which website had the most visits in 2017?',
      'What city has the largest population in the world?',
      'What occurs at 212 degrees Fahreneheit',
      'What landmark American achievement occurred in 1969?',
      'What hotel was behind the Nixon scandal?',
      'What is the richest soccer club in the world?',
      'What is the highest grossing movie of all time?',
      'Who directed Inception?',
      'What is Darth Vader\'s first name?',
      'In what movie did Biff steal a sports almanac?',
      'What is the name of the Elven realm in the Lord of the Rings movie?',
      'What character was played by Carrie-Anne Moss in the Matrix?',
      'Who is the highest paid TV actress?',
      'What is the fourth largest state by size in the US?',
      'What is the second most populated state in the US?',
      'What is Tom Cruise\'s highest grossing movie?',
      'What country shares a border with the most other countries?'
    ],
    subtopics: [
      'Albany',
      'Justin Trudeau',
      'John F Kennedy',
      'The Hippopotamus',
      'Petunia',
      'Nigeria',
      'Monica',
      'Absolute Zero',
      'Rex Tillerson',
      '64',
      'Dracula',
      'Charlie Chaplan',
      'Cristiano Ronaldo',
      'Golden State Warriors',
      'Google',
      'Tokyo',
      'Water Boils',
      'Landed on the Moon',
      'Watergate',
      'Manchester United',
      'Avatar',
      'Christopher Nolan',
      'Anakin',
      'Back to the Future',
      'Rivendell',
      'Trinity',
      'Sofia Vergara',
      'Montana',
      'Texas',
      'Top Gun',
      'China'
    ]
  },
  {
    title: 'Rhyme',
    completed: 'Losing',
    directions: 'Each player or team must say a word\nthat rhymes with the given word',
    style: {},
    modes: ['duel', 'FFA', 'team'],
    topics: [
      'Ball',
      'Floor',
      'Game',
      'Mug',
      'Tail',
      'Eight',
      'Drop',
      'Real',
      'Shoe',
      'Fear',
      'Roll',
      'Tree',
      'Feet',
      'Rock',
      'Seek'
    ]
  },
  {
    title: 'Simon Says',
    completed: 'Losing',
    directions: 'Shout out "Simon says" and name a gesture.\nThe last player to make the gesture loses.',
    style: {},
    modes: ['FFA'],
    topics: [
      'Play!',
      'Play!',
      'Play!',
      'Play!',
      'Play!',
    ]
  },
  {
    title: 'Drive',
    completed: 'Losing',
    directions: 'Everyone puts their hands up to imitate driving a car.\n\nStart gameplay by shouting "Vroom" and turning your hands to the left or right.\nThe "driver" is passed to the player next to you in that direction.\n\nThe "driver" can either say "Vroom" and turn their hands to continue passing to the same direction, or "Skert", passing the "driver" in the opposite direction.',
    style: {fontSize: 18, textAlign: 'left'},
    modes: ['FFA'],
    topics: [
      'Begin Driving!',
      'Begin Driving!',
      'Begin Driving!'
    ]
  },
  {
    title: 'Going to the Moon',
    completed: 'Losing',
    directions: 'Start the game by saying:\n"I\'m going to the moon, and I\'m bringing (e.g.) an apple."\nThe next player would then say:\n"I\'m going to the moon, and I\'m bringing an apple and a radio."\n\nPlayers must remember and list all items said before them, as well as their own item, without pausing for more than 3 seconds.',
    style: {},
    modes: ['FFA', 'duel'],
    topics: [
      'Begin!',
      'Begin!',
    ]
  },

]
